[package]
name = "mrml-kernel-image"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
kernel-image = []
fault-probe = ["kernel-image"]
timer-probe = ["kernel-image"]
preemption-probe = ["kernel-image"]
service-preemption-probe = ["kernel-image"]
user-probe = ["kernel-image"]
service-probe = ["kernel-image"]
production-policy = ["kernel-image"]
gpu-benchmark = ["kernel-image"]
whp-gpu-benchmark = ["gpu-benchmark"]
emulated-ap-timing = ["kernel-image"]
ap-startup-trace = ["emulated-ap-timing"]
smp-probe = ["kernel-image"]
whp-smp-probe = ["smp-probe", "ap-startup-trace"]
smp-scheduler-probe = ["kernel-image", "emulated-ap-timing", "ap-startup-trace"]
whp-smp-scheduler-probe = ["smp-scheduler-probe"]

[[bin]]
name = "mrml-kernel-pe"
path = "src/main.rs"
test = false
bench = false
required-features = ["kernel-image"]

[dependencies]
mrml-kernel = { path = "../mrml-kernel" }
