[package]
name = "mrml-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "mrml-cli"
path = "src/main.rs"

[features]
default = ["auto"]
auto = ["mrml-agent/auto"]
cuda = ["mrml-agent/cuda"]
vulkan = ["mrml-agent/vulkan"]
hipblas = ["mrml-agent/hipblas"]
sycl = ["mrml-agent/sycl"]

[dependencies]
mrml-agent = { path = "../mrml-agent", default-features = false, features = ["runtime"] }
mrml-tools = { path = "../mrml-tools" }
mrml-terminal-style = { path = "../mrml-terminal-style" }
mrml-runtime = { path = "../mrml-runtime" }
mrml-error = { path = "../mrml-error" }
