[workspace]
resolver = "2"
members = [
    "crates/mrml-runtime",
    "crates/mrml-model",
    "crates/mrml-math",
    "crates/mrml-tensor",
    "crates/mrml-core",
    "crates/mrml-cli",
    "crates/mrml-machine",
    "crates/mrml-anyhow",
    "crates/mrml-server",
    "crates/mrml-terminal-style",
    "crates/mrml-tools",
    "crates/mrml-urlencoding",
    "crates/mrml-windows",
    "crates/mrml-linux",
    "crates/mrml-json",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
authors = ["Mitchell Renouf <mitchell@localhost>"]
license = "CC0-1.0"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
