[workspace]
resolver = "2"
members = [
    "crates/mrml-runtime",
    "crates/mrml-model",
    "crates/mrml-math",
    "crates/mrml-tensor",
    "crates/mrml-agent",
    "crates/mrml-cli",
    "crates/mrml-machine",
    "crates/mrml-error",
    "crates/mrml-server",
    "crates/mrml-terminal-style",
    "crates/mrml-tools",
    "crates/mrml-percent-encoding",
    "crates/mrml-windows",
    "crates/mrml-linux",
    "crates/mrml-json",
    "crates/mrml-zim",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
authors = ["Mitchell Renouf <mitchell@localhost>"]
license = "CC0-1.0"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
strip = "symbols"

[profile.dev]
panic = "abort"
