[package]
name = "llamarust-qt"
version.workspace = true
edition.workspace = true
authors.workspace = true
build = "build.rs"
autobins = false

[features]
default = ["auto"]
auto = ["llamarust-core/auto"]
cuda = ["llamarust-core/cuda"]
vulkan = ["llamarust-core/vulkan"]

[dependencies]
llamarust-core = { path = "../llamarust-core", default-features = false }
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
futures-util.workspace = true
serde_json.workspace = true
tokio.workspace = true
qtrs = "0.5.7"
tokio-tungstenite = "0.26"
tungstenite = "0.26"

[[bin]]
name = "rustllama"
path = "src/main.rs"
