[package]
name = "mrml-machine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "mrml-machine"
path = "src/main.rs"

[features]
default = ["auto"]
auto = ["mrml-core/auto"]
cuda = ["mrml-core/cuda"]
vulkan = ["mrml-core/vulkan"]
hipblas = ["mrml-core/hipblas"]
sycl = ["mrml-core/sycl"]

[dependencies]
mrml-core = { path = "../mrml-core", default-features = false }
mrml-json = { path = "../mrml-json" }
mrml-tools = { path = "../mrml-tools" }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow" }
