[package]
name = "rustllama-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "rustllama"
path = "src/main.rs"

[features]
default = ["auto"]
auto = ["rustllama-core/auto"]
cuda = ["rustllama-core/cuda"]
vulkan = ["rustllama-core/vulkan"]

[dependencies]
rustllama-core = { path = "../rustllama-core", default-features = false }
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
futures-util.workspace = true
llama-rs = { path = "../llama-rs" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite = "0.26"
tungstenite = "0.26"
