[package]
name = "mrml-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "mrml-server"
path = "src/main.rs"

[features]
default = ["auto"]
auto = ["mrml-core/auto"]
cuda = ["mrml-core/cuda"]
vulkan = ["mrml-core/vulkan"]

[dependencies]
mrml-core = { path = "../mrml-core", default-features = false }
mrml-terminal-style = { path = "../mrml-terminal-style" }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow" }
clap.workspace = true
mrml-model = { path = "../mrml-model" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
