[package]
name = "mrml-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "mrml-server"
path = "src/main.rs"

[features]
default = ["auto"]
auto = ["mrml-agent/auto"]
cuda = ["mrml-agent/cuda"]
vulkan = ["mrml-agent/vulkan"]

[dependencies]
mrml-agent = { path = "../mrml-agent", default-features = false, features = ["runtime"] }
mrml-terminal-style = { path = "../mrml-terminal-style" }
mrml-error = { path = "../mrml-error" }
mrml-model = { path = "../mrml-model" }
mrml-json = { path = "../mrml-json" }
mrml-tools = { path = "../mrml-tools" }
mrml-runtime = { path = "../mrml-runtime" }
