[package]
name = "llamarust-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["auto"]
auto = ["llama-rs/auto"]
cuda = ["llama-rs/cuda"]
vulkan = ["llama-rs/vulkan"]
hipblas = ["llama-rs/hipblas"]
sycl = ["llama-rs/sycl"]

[dependencies]
llama-rs = { path = "../llama-rs" }
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
colored.workspace = true
futures-util.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
walkdir = "2.5"
urlencoding = "2.1"
similar = "3.1"
scraper = "0.27"
termimad = "0.35"
dirs = "6.0"
chromiumoxide = { version = "0.9.1", features = ["fetcher", "rustls", "zip8"] }
tokio-tungstenite = "0.26"
