[package]
name = "mrml-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["auto"]
auto = ["mrml-model/auto"]
cuda = ["mrml-model/cuda"]
vulkan = ["mrml-model/vulkan"]
hipblas = ["mrml-model/hipblas"]
sycl = ["mrml-model/sycl"]

[dependencies]
mrml-model = { path = "../mrml-model" }
mrml-terminal-style = { path = "../mrml-terminal-style" }
mrml-tools = { path = "../mrml-tools" }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
