[package]
name = "mrml-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["std", "auto"]
std = ["mrml-model/std", "mrml-terminal-style/std", "mrml-tools/std"]
auto = ["std", "mrml-model/auto"]
cuda = ["std", "mrml-model/cuda"]
vulkan = ["std", "mrml-model/vulkan"]
hipblas = ["std", "mrml-model/hipblas"]
sycl = ["std", "mrml-model/sycl"]

[dependencies]
mrml-model = { path = "../mrml-model", default-features = false }
mrml-terminal-style = { path = "../mrml-terminal-style", default-features = false }
mrml-tools = { path = "../mrml-tools", default-features = false }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow" }
serde_json = { package = "mrml-json", path = "../mrml-json" }
