[package]
name = "rustllama-qt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
build = "build.rs"
autobins = false

[features]
default = ["auto"]
auto = ["rustllama-core/auto"]
cuda = ["rustllama-core/cuda"]
vulkan = ["rustllama-core/vulkan"]

[dependencies]
rustllama-core = { path = "../rustllama-core", default-features = false }
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
futures-util.workspace = true
serde_json.workspace = true
tokio.workspace = true
qtrs = "0.5.7"
tokio-tungstenite = "0.26"
tungstenite = "0.26"

[[bin]]
name = "rustllama-qt"
path = "src/main.rs"
