[package]
name = "mrml-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["runtime"]
runtime = [
    "dep:mrml-error",
    "dep:mrml-terminal-style",
    "dep:mrml-runtime",
    "dep:serde_json",
    "dep:mrml-percent-encoding",
    "dep:mrml-linux",
    "dep:mrml-windows",
    "dep:mrml-http",
]

[dependencies]
mrml-terminal-style = { path = "../mrml-terminal-style", default-features = false, optional = true }
mrml-error = { path = "../mrml-error", optional = true }
serde_json = { package = "mrml-json", path = "../mrml-json", optional = true }
mrml-percent-encoding = { path = "../mrml-percent-encoding", optional = true }
mrml-runtime = { path = "../mrml-runtime", optional = true }
mrml-http = { path = "../mrml-http", optional = true }

[target.'cfg(windows)'.dependencies]
mrml-windows = { path = "../mrml-windows", optional = true }

[target.'cfg(unix)'.dependencies]
mrml-linux = { path = "../mrml-linux", optional = true }
