[package]
name = "mrml-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["std"]
runtime = [
    "dep:anyhow",
    "dep:mrml-terminal-style",
    "dep:mrml-runtime",
    "dep:serde_json",
    "dep:urlencoding",
]
std = [
    "runtime",
    "dep:mrml-linux",
    "dep:mrml-windows",
    "mrml-terminal-style/std",
]

[dependencies]
mrml-terminal-style = { path = "../mrml-terminal-style", default-features = false, optional = true }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow", optional = true }
serde_json = { package = "mrml-json", path = "../mrml-json", optional = true }
urlencoding = { package = "mrml-urlencoding", path = "../mrml-urlencoding", optional = true }
mrml-runtime = { path = "../mrml-runtime", optional = true }

[target.'cfg(windows)'.dependencies]
mrml-windows = { path = "../mrml-windows", optional = true }

[target.'cfg(unix)'.dependencies]
mrml-linux = { path = "../mrml-linux", optional = true }
