[package]
name = "mrml-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mrml-terminal-style = { path = "../mrml-terminal-style" }
anyhow = { package = "mrml-anyhow", path = "../mrml-anyhow" }
async-trait.workspace = true
futures-util.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
urlencoding = { package = "mrml-urlencoding", path = "../mrml-urlencoding" }
scraper = "0.27"
chromiumoxide = { version = "0.9.1", features = ["fetcher", "rustls", "zip8"] }
