[package]
name = "mrml-terminal-style"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
mrml-runtime = { path = "../mrml-runtime" }

[target.'cfg(windows)'.dependencies]
mrml-windows = { path = "../mrml-windows" }

[target.'cfg(unix)'.dependencies]
mrml-linux = { path = "../mrml-linux" }
