[package]
name = "mrml-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["runtime"]
runtime = [
    "dep:mrml-error",
    "dep:mrml-model",
    "dep:mrml-terminal-style",
    "dep:mrml-tools",
    "dep:serde_json",
    "dep:mrml-http",
    "dep:mrml-crypto",
    "mrml-model/runtime",
    "mrml-tools/runtime",
]
auto = ["runtime", "mrml-model/auto"]
cuda = ["runtime", "mrml-model/cuda"]
vulkan = ["runtime", "mrml-model/vulkan"]
hipblas = ["runtime", "mrml-model/hipblas"]
sycl = ["runtime", "mrml-model/sycl"]

[dependencies]
mrml-model = { path = "../mrml-model", default-features = false, optional = true }
mrml-terminal-style = { path = "../mrml-terminal-style", default-features = false, optional = true }
mrml-tools = { path = "../mrml-tools", default-features = false, optional = true }
mrml-error = { path = "../mrml-error", optional = true }
serde_json = { package = "mrml-json", path = "../mrml-json", optional = true }
mrml-runtime = { path = "../mrml-runtime" }
mrml-http = { path = "../mrml-http", optional = true }
mrml-crypto = { path = "../mrml-crypto", optional = true }
